import { Landlord, Listing, TenantProfile } from "@/lib/types";

export const berlinLandlords: Landlord[] = [
    {
        id: "ld-1001",
        name: "UrbanHaus GmbH",
        type: "company",
        email: "kontakt@urbanhaus.example",
        website: "https://urbanhaus.example",
    },
    {
        id: "ld-1002",
        name: "Brix Property",
        type: "company",
        email: "hello@brix-property.example",
        website: "https://brix-property.example",
    },
    {
        id: "ld-1003",
        name: "R. Fischer",
        type: "private",
    },
    {
        id: "ld-2001",
        name: "Berliner Heim eG",
        type: "genossenschaft",
        email: "service@berliner-heim.example",
        website: "https://berliner-heim.example",
    },
    {
        id: "ld-2002",
        name: "NordWohn eG",
        type: "genossenschaft",
        email: "kontakt@nordwohn.example",
        website: "https://nordwohn.example",
    },
];

export const berlinListings: Listing[] = [
    {
        id: "l-1001",
        title: "Bright 2-room in Prenzlauer Berg",
        district: "Prenzlauer Berg",
        address: "Knaackstrasse 17, 10405 Berlin",
        monthlyRentEur: 1280,
        sizeM2: 54,
        rooms: 2,
        source: "immobilienscout24",
        landlordId: "ld-1001",
        landlordName: "UrbanHaus GmbH",
        commuteMinutesToCenter: 18,
        noiseScore: 34,
        vibeTags: ["cafes", "young", "walkable"],
    },
    {
        id: "l-1002",
        title: "Family flat near Tempelhofer Feld",
        district: "Neukoelln",
        address: "Oderstrasse 6, 12051 Berlin",
        monthlyRentEur: 1650,
        sizeM2: 79,
        rooms: 3,
        source: "immowelt",
        landlordId: "ld-1002",
        landlordName: "Brix Property",
        commuteMinutesToCenter: 22,
        noiseScore: 49,
        vibeTags: ["parks", "family", "diverse"],
    },
    {
        id: "l-1003",
        title: "Compact studio in Moabit",
        district: "Moabit",
        address: "Turmstrasse 85, 10551 Berlin",
        monthlyRentEur: 890,
        sizeM2: 31,
        rooms: 1,
        source: "kleinanzeigen",
        landlordId: "ld-1003",
        landlordName: "R. Fischer",
        commuteMinutesToCenter: 16,
        noiseScore: 57,
        vibeTags: ["central", "busy", "nightlife"],
    },
    {
        id: "l-2001",
        title: "Genossenschaft apartment in Lichtenberg",
        district: "Lichtenberg",
        address: "Siegfriedstrasse 112, 10365 Berlin",
        monthlyRentEur: 980,
        sizeM2: 58,
        rooms: 2,
        source: "genossenschaft",
        landlordId: "ld-2001",
        genossenschaftName: "Berliner Heim eG",
        landlordName: "Berliner Heim eG",
        commuteMinutesToCenter: 26,
        noiseScore: 29,
        vibeTags: ["quiet", "green", "residential"],
    },
    {
        id: "l-2002",
        title: "Genossenschaft family unit in Pankow",
        district: "Pankow",
        address: "Breite Strasse 45, 13187 Berlin",
        monthlyRentEur: 1320,
        sizeM2: 84,
        rooms: 3,
        source: "genossenschaft",
        landlordId: "ld-2002",
        genossenschaftName: "NordWohn eG",
        landlordName: "NordWohn eG",
        commuteMinutesToCenter: 24,
        noiseScore: 33,
        vibeTags: ["schools", "quiet", "family"],
    },
];

export const districtRentBenchmarkPerM2: Record<string, number> = {
    "Prenzlauer Berg": 22,
    Neukoelln: 19,
    Moabit: 20,
    Lichtenberg: 16,
    Pankow: 18,
};

export const demoTenant: TenantProfile = {
    id: "tn-1001",
    name: "Alex Meyer",
    email: "alex@example.com",
    monthlyNetIncomeEur: 3600,
    householdSize: 2,
    hasPets: false,
    hasSchufa: true,
    stableEmploymentMonths: 28,
    preferredDistricts: ["Pankow", "Prenzlauer Berg", "Lichtenberg"],
};
